### PR TITLE
Use @electron/remote instead of importing it from electron as it will be deprecated in Electron version 14

### LINKED ISSUE #76: Use `@electron/remote` instead of importing it from `electron` as it will be deprecated in Electron version 14
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

The latest version of Electron, 14 has deprecated the `{remote}` import from the `electron` package and they created another package for it, `@electron/remote`. using `electron.remote` will cause an error saying it's undefined. So, please update it to avoid errors.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/electron-prompt/lib/index.js b/node_modules/electron-prompt/lib/index.js
index 871b75f..c5caf23 100644
--- a/node_modules/electron-prompt/lib/index.js
+++ b/node_modules/electron-prompt/lib/index.js
@@ -1,7 +1,7 @@
 const electron = require('electron');
-
-const BrowserWindow = electron.BrowserWindow || electron.remote.BrowserWindow;
-const ipcMain = electron.ipcMain || electron.remote.ipcMain;
+const remote = require("@electron/remote");
+const BrowserWindow = electron.BrowserWindow || remote.BrowserWindow;
+const ipcMain = electron.ipcMain || remote.ipcMain;
 const url = require('url');
 const path = require('path');
 
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

### PR DESCRIPTION
**Pull request by kimlimjustin**
resolve #76

### CODE REVIEW

**Comment by andyvalerio** [comment]
Nice, I was about to do it myself! +1

**Comment by p-sam** [comment]
Hi, thanks for the PR. Since workflows seemed to be gone on PRs, please rebase on develop, that might fix it, but you may have to fix your code style to fix the errors. You also forgot to remove a leftover from your tests, please remove the 'yarn.lock' file

**Comment by kimlimjustin** [comment]
> Hi, thanks for the PR. Since workflows seemed to be gone on PRs, please rebase on develop, that might fix it, but you may have to fix your code style to fix the errors. You also forgot to remove a leftover from your tests, please remove the 'yarn.lock' file

Okay, it's basically just the double-quoted and single-quoted string problem tho haha, I'll fix it, btw for the `yarn.lock`, why don't you just put it into `.gitignore`. In addition, for the workflow, I think it's better to create a GitHub workflow to let future PR get checked immediately.

**Comment by p-sam** [comment]
@kimlimjustin Yes there's a workflow and that's why I asked you to rebase. You don't get to have it automatically happen since it's your first contribution though. LGTM

**Pull request merged**
