### PR TITLE
Add: flexible window sizing to opts

### PR DESCRIPTION
**Pull request by lbell**
This does require some tweaking to the CSS that I have tried to make as non-breaking as possible (though may force some users to specify a height to get rid of scroll bars)

### CODE REVIEW

**Comment by p-sam** [comment]
Thanks for the PR. While the initial goal seems ok with me I have a few questions:
* Would it not also mean it should permit resizing? I believe custom sizing and being able to resize the window are tied together.
* Why not leave the width and height that were here before as the defaults ones?

**Comment by lbell** [comment]
Happy to brainstorm:

- I call the prompt window several different times in my program, each needing their own size -- but none needing to be re-sizeable. Adding re-sizable as an option would be super-easy though, and increase the flexibility:
```
const opts = Object.assign({
  width: 370,
  height: 130,
  resizable: false,
  title: 'Prompt',
  ...(etc)
```
```
let promptWindow = new BrowserWindow({
  width: opts.width,
  height: opts.height,
  resizable: opts.resizable,
  ... (ect)
```

- I thought the original width and height were left as default (see above: line 12 & 13 of opts in index.js)

**Comment by p-sam** [comment]
It seems I totally missed the properties in Object.assign, that's great then.
I'm ok with the "resizable" properties in opts, we can probably merge after that included.

**Comment by p-sam** [comment]
I'm sorry I totally forgot about you, I will merge that later today

**Pull request merged**
