### PR TITLE
Fixes #3

### LINKED ISSUE #3: Error when trying to use this for the first time...
Something is wrong with the ParentWindow

```
electron-prompt/lib/index.js:21
Uncaught (in promise) TypeError: Right-hand side of 'instanceof' is not an object
```

code that caused it:
```
prompt({
	title: 'Why is this item being added?',
	label: 'Reason',
	value: 'Customer Wanted to calibrate it',
	inputAttrs: {
		type: 'text',
		width: '200px',
		height: '250px'
	}
})
```

### PR DESCRIPTION
**Pull request by alandoyle95**

### CODE REVIEW

**Comment by p-sam** [comment]
I didn't know you were using it from the renderer context, hence why you added electron.remote.BrowserWindow.
Thanks for the PR, will merge & publish

**Comment by alandoyle95** [comment]
oh yea.. forgot to mention that :D haha my bad

**Comment by alandoyle95** [comment]
any update on this? lol just wondering :)

**Comment by p-sam** [comment]
I just needed to test some more uses cases, nearly good to go :)

**Comment by alandoyle95** [comment]
awesome :) thanks!

**Comment by p-sam** [comment]
published in 0.3.0

**Pull request merged**
